<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>10</LangVersion>
		<IsPackable>false</IsPackable>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>..\MDD4All.EAFacade.DataAccess.Cached\MDD4All_Github.snk</AssemblyOriginatorKeyFile>
		<PlatformTarget>x86</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="xunit" Version="2.9.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MDD4All.EAFacade.DataAccess.Cached\MDD4All.EAFacade.DataAccess.Cached-dev.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Interop.EA">
			<HintPath>..\libs\Interop.EA.dll</HintPath>
			<EmbedInteropTypes>false</EmbedInteropTypes>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Update="Assets\Empty.eapx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
